# The URL the site will be built for
base_url = "https://jiaxiang.wang"

title = "ä¸ªäººä¸»é¡µ"

author = "ç‹å˜‰ç¥¥"

description = "å¥½å¥‡ã€æ¢ç´¢ã€åˆ›é€ ã€‚ä¸ªäººä¸»é¡µå¯¼èˆªç½‘ç«™ã€‚"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

minify_html = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]

[extra.site]
start_year = 2024
logo = "/img/logo.webp"
# default to use logo value
nav_logo = "/img/logo.webp"
icp = "ICPå¤‡XXXXXXXXå·"

# umami è®¿é—®é‡ç»Ÿè®¡
[extra.analytics.umami]
enable = false
# ç”Ÿæ•ˆçš„åŸŸåï¼Œé¿å…è¢« localhost ç»Ÿè®¡
domain = "example.com"
# è‡ªå·±çš„umamiæœåŠ¡åœ°å€
remote_url = "https://umami-api"
#remote_url = "https://umami-wangjiaxiang-d12g.netlify.app"
# ç½‘ç«™id
id = "5c123448-a501-444c-830a-e55df930cd4a"
# js åŠ è½½åœ°å€
js = "/path/to/script.js"

[extra.nav]

[extra.nav.message]
enable = true
# support inline html
text = "ğŸ‰ åšå®¢ç°å·²ä¸Šçº¿"
url = "https://blog.jiaxiang.wang"

[extra.nav.center]
menus = [
    { name = "ä¸»é¡µ", url = "ä¸»é¡µ", internal = true},
    { name = "ä¸»é¢˜", url = "ä¸»é¢˜", internal = true},
    { name = "åšå®¢", url = "åšå®¢", internal = true},
    { name = "åª’ä½“", url = "åª’ä½“", internal = true},
    { name = "é¡¹ç›®", url = "https://blog.jiaxiang.wang/tags/project/", internal = false},
]

[extra.nav.right]
menus = [
    { name = "è®¿é—®åšå®¢", url = "https://blog.jiaxiang.wang", internal = false},
    { name = "Github", url = "https://github.com/iWangJiaxiang", internal = false},
]


# ä¸»é¡µå°ç»„ä»¶ æŒ‰é¡ºåºæ¸²æŸ“
[[extra.index.widgets]]
type = "header"
[extra.index.widgets.value]
title_1 = "ç‹å˜‰ç¥¥"
title_2 = "Jiaxiang Wang"
bio_1 = "ä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸ<span class=\"inline-word\">è·¨ç•Œåˆ›æ–°</span>"
bio_2 = "åˆ†äº«ç»éªŒä¸è§è§£"
about_url = "https://blog.jiaxiang.wang/about/"
cover = "/img/logo.svg"
[[extra.index.widgets.value.links]]
class_icon = " icon-github-line"
url = "https://github.com/iWangJiaxiang"
[[extra.index.widgets.value.links]]
class_icon = " icon-github-line"
url = "https://github.com/iWangJiaxiang"


[[extra.index.widgets]]
type = "author"
[extra.index.widgets.value]
name = "ç‹å˜‰ç¥¥"
avatar = "/img/logo01.webp"
title = "Team leader, architect,"
# title = "Team leader, architect, senior engineer, singer songwriter, creator. Engaging in HPC, Cloud, AI and more."
bio = "â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€â€œä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£â€"


[[extra.index.widgets]]
type = "product-single"
[extra.index.widgets.value]
tip = "ä¸»é¡µ"
title = "ä¸ªäººä¸»é¡µ<br>æ­£å¼å¼€æº"
bio_1 = "åƒæœ¬é¡µé¢ä¸€æ ·ï¼Œå‘ˆç°ç¾è½®ç¾å¥‚<span class=\"inline-word\">æ•ˆæœ</span>"
bio_2 = "è½»æ¾é…ç½®ï¼Œå¿«é€Ÿæ„å»ºä½ çš„<span class=\"inline-word\">ä¸ªäººä¸»é¡µ</span>"
img = "/img/homepage-single.avif"
[[extra.index.widgets.value.links]]
class = "primary-button"
url = "https://github.com/iWangJiaxiang/Homepage-Creators"
name = "ç«‹åˆ»è·å–æºä»£ç "
[[extra.index.widgets.value.links]]
class = "second-link"
url = "https://github.com/iWangJiaxiang"
name = "å¼€å‘è€…ä¸»é¡µ"


[[extra.index.widgets]]
type = "event"
[extra.index.widgets.value]
tip = "å¤§äº‹ä»¶"
title = "ç‹å˜‰ç¥¥åšå®¢ä¸»é¢˜<br>æ­£å¼å¼€æºï¼"
bio = "ä¸€ä¸ªä¸ºåˆ›ä½œè€…è€Œæ„å»ºçš„ä¸»é¢˜ï¼Œ0æˆæœ¬ã€0è¿ç»´å¼€å§‹ä½ çš„åšå®¢ç”Ÿæ¶¯ï¼Œä¸å„ä½ä¼˜ç§€åšä¸»ä¸€åŒè¿›æ­¥ï¼"
button = "ç«‹åˆ»è·å–æºä»£ç "
note = "åŸºäº Zola æ„å»º"
url = "https://github.com/iWangJiaxiang/zola-theme-jiaxiang.wang"
img = "/img/blog-event.avif"


[[extra.index.widgets]]
type = "product-single"
[extra.index.widgets.value]
tip = "åšå®¢"
title = "æ–°å¥‡çš„äº‹ç‰©<br>æœ‰è¶£çš„æ€æƒ³"
bio_1 = "å¤‡å—å–œçˆ±çš„çŸ¥è¯†å…±äº«<span class=\"inline-word\">åšå®¢</span>"
bio_2 = "å·²å¸®åŠ©æ•°ç™¾ä¸‡äº’è”ç½‘ä½¿ç”¨è€…æ›´å¥½çš„æ¢ç´¢æ•°å­—<span class=\"inline-word\">ä¸–ç•Œ</span>"
img = "/img/blog.avif"
style = "background-image: linear-gradient(180deg, #830FC1 0%, #3D00A0 100%);"
[[extra.index.widgets.value.links]]
class = "primary-button"
url = "https://blog.jiaxiang.wang/"
name = "è®¿é—®åšå®¢"
[[extra.index.widgets.value.links]]
class = "second-link"
url = "https://blog.jiaxiang.wang/articles/misc/from-0-to-1-the-blog-review/"
name = "åˆ›ç«™æ•…äº‹"


[[extra.index.widgets]]
type = "product-list"
[extra.index.widgets.value]
title = "åª’ä½“"
bio = "ä¸ºäº’è”ç½‘å…±äº«ç²¾ç¥æ·»ç –åŠ ç“¦"
[[extra.index.widgets.value.items]]
logo = "/img/internet.svg"
title = "ä¸ªäººåšå®¢"
bio = "ä¸“æ³¨äºç§‘æŠ€ã€éŸ³ä¹ç­‰é¢†åŸŸè·¨ç•Œåˆ›æ–°ï¼Œåˆ†äº«ç»éªŒä¸è§è§£"
url = "https://blog.jiaxiang.wang/"
button = "è®¿é—®"
[[extra.index.widgets.value.items]]
logo = "/img/afdian.png"
title = "çˆ±å‘ç”µ"
bio = "åˆ†äº«æœ‰è¶£åˆæœ‰æ–™çš„æ–‡ç« ä¸èµ„æº"
url = "https://afdian.com/a/wangjiaxiang"
button = "è®¿é—®"
note = "è®¢é˜…åˆ¶"
new = true
[[extra.index.widgets.value.items]]
logo = "/img/wechat.svg"
title = "å…¬ä¼—å·"
bio = "ç¬¬ä¸€æ—¶é—´è·å–åŠ¨æ€"
url = "https://blog.jiaxiang.wang/wechat"
button = "è®¿é—®"
hot = true
[[extra.index.widgets.value.items]]
logo = "/img/follow.svg"
title = "Follow"
bio = "ä¸€ç«™å¼è·å–æ–‡ç« è®¢é˜…"
url = "https://app.follow.is/share/feeds/89889813571729408"
button = "è®¿é—®"
new = true


[[extra.index.widgets]]
type = "product-single"
[extra.index.widgets.value]
tip = "ä¸»é¢˜"
title = "åšå®¢ä¸»é¢˜<br>å¼€æºå…±äº«"
bio_1 = "0æˆæœ¬0è¿ç»´æ­å»ºå±äºä½ çš„<span class=\"inline-word\">åšå®¢ç«™ç‚¹</span>"
bio_2 = "è¿›å…¥åˆ›ä½œåˆ†äº«çš„<span class=\"inline-word\">åšå®¢ä¸–ç•Œ</span>"
img = "/img/theme-single.avif"
style = "background-image: linear-gradient(180deg, #0F6AC1 0%, #002EA0 100%);"
style_tip = "color: white; opacity: 0.6;"
[[extra.index.widgets.value.links]]
class = "primary-button"
url = "https://github.com/iWangJiaxiang/zola-theme-jiaxiang.wang"
name = "è®¿é—®é¡¹ç›®"
[[extra.index.widgets.value.links]]
class = "second-link"
url = "https://theme.jiaxiang.wang/"
name = "è®¿é—®æ¼”ç¤ºç«™ç‚¹"


[[extra.index.widgets]]
type = "product-list"
[extra.index.widgets.value]
title = "ä¸»é¢˜"
bio = "å¸®åŠ©æ›´å¤šç”¨æˆ·æ„å»ºå‡ºéå‡¡çš„ç½‘ç«™"
[[extra.index.widgets.value.items]]
logo = "/img/internet.svg"
title = "Jiaiang.Wang"
bio = "çº¯é™æ€ä¸ªäººåšå®¢ä¸»é¢˜ (Zola)"
url = "https://github.com/iWangJiaxiang/zola-theme-jiaxiang.wang"
button = "è®¿é—®"
note = "æœ¬äººåšå®¢ä¸»é¢˜"
hot = true
[[extra.index.widgets.value.items]]
logo = "/img/internet.svg"
title = "Homepage Creators"
bio = "çº¯é™æ€ä¸ªäººä¸»é¡µä¸»é¢˜ (Zola)"
url = "https://github.com/iWangJiaxiang/Homepage-Creators"
button = "è®¿é—®"
note = "æœ¬ç«™ä¸»é¢˜"
new = true